services:
  solenra:
    image: solenra:latest
    container_name: solenra
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    env_file:
    - .env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:file:/data/solenra.h2.db
      - SPRING_H2_CONSOLE_ENABLED=true
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    volumes:
      - ${DB_DATA_LOCATION:-solenra-data}:/data

volumes:
  solenra-data: